Fixed modifying Pip commands on native Windows with Python 3.8
Details:

* The installation of setuptools, wheel and other packages such as six
  on Appveyor (native Windows) with Python 3.8 using the 'pip install'
  command failed with the error:

    ERROR: To modify pip, please run the following command:
    ...\python.exe -m pip install ...

  Pip issue https://github.com/pypa/pip/issues/6994 hints that this may
  be related to packages that require pip. Pip itself vendors any
  dependencies, so that cannot be the reason. however, the error also
  is raised for packages such as six that do not require pip.

  It turned out that in other projects, we have already used
  "python -m pip install ...", but did not document why.

  Anyway, changed any modifying invocation of "pip" to become
  "python -m pip", by introducing an according Make variable
  PIP_CMD_MOD.

Signed-off-by: Andreas Maier <andreas.r.maier@gmx.de>